### ISSUE TITLE
Could not find com.github.Chocohead:Fabric-ASM:v2.0

### ISSUE THREAD

**Issue by EucloidMC** [Chocohead/Fabric-ASM#10]
> Could not resolve all files for configuration ':modCompileClasspath'.
   > Could not find com.github.Chocohead:Fabric-ASM:v2.0.
     Searched in the following locations:
       - file:/C:/Users/V0pT/Documents/GitHub/The-Backrooms-Mod/build/loom-cache/Fabric-ASM-v2.0.jar
       - file:/C:/Users/V0pT/Documents/GitHub/The-Backrooms-Mod/build/loom-cache/Fabric-ASM.jar
       - file:/C:/Users/V0pT/Documents/GitHub/The-Backrooms-Mod/.gradle/loom-cache/remapped_mods/com/github/Chocohead/Fabric-ASM/v2.0/Fabric-ASM-v2.0.pom
       - https://maven.fabricmc.net/com/github/Chocohead/Fabric-ASM/v2.0/Fabric-ASM-v2.0.pom
       - https://libraries.minecraft.net/com/github/Chocohead/Fabric-ASM/v2.0/Fabric-ASM-v2.0.pom
       - https://repo.maven.apache.org/maven2/com/github/Chocohead/Fabric-ASM/v2.0/Fabric-ASM-v2.0.pom
       - file:/C:/Users/V0pT/.gradle/caches/fabric-loom/v2.0/Fabric-ASM-v2.0.jar
       - file:/C:/Users/V0pT/Documents/GitHub/The-Backrooms-Mod/.gradle/loom-cache/v2.0/Fabric-ASM-v2.0.jar
       - https://maven.terraformersmc.com/com/github/Chocohead/Fabric-ASM/v2.0/Fabric-ASM-v2.0.pom
       - https://maven.shedaniel.me/com/github/Chocohead/Fabric-ASM/v2.0/Fabric-ASM-v2.0.pom
       - https://server.bbkr.space/artifactory/libs-release/com/github/Chocohead/Fabric-ASM/v2.0/Fabric-ASM-v2.0.pom

I checked the TerraformersMC maven page and Fabric ASM seems to be gone. Maybe it's been moved?
the old page was maven.terraformersmc.com/com/github/Chocohead/Fabric-ASM/,
however there is no maven.terraformersmc.com/com/github anymore.

**Comment by Synchlabs** [comment]
It seems as if the TerraformersMC maven page is down.

**Comment by EucloidMC** [comment]
EDIT: Nevermind, it uses jitpack not terraformers maven. I added back jitpack and it works.
