### ISSUE TITLE
ClassTinkerers.addTransformation doesnt seem to work on interfaces

### ISSUE THREAD

**Issue by modmuss50** [Chocohead/Fabric-ASM#2]
ClassTinkerers.addTransformation does not seem to work on interfaces.

https://gist.github.com/modmuss50/d4db2559bb8c9baa3c91c5ae63b28f7a

**Comment by modmuss50** [comment]
I think the generated class needs to be an interface, might need a add interface transformer or something.

**Comment by Chocohead** [comment]
When I first wrote MM Mixin didn't allow for injecting into interfaces at all. Should work for everything with v1.5
